---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
  namespace: default
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: hello

      # annotations:
      #   prometheus.io/scrape: 'false'
      #   prometheus.io/port: '8081'

    spec:

      # securityContext:
      #   runAsNonRoot: true
      #   runAsUser: 1000

      restartPolicy: Always
      containers:
        - name: hello
          image: starkers/hello:latest
          ports:
          - name: web
            containerPort: 8080

          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8081
          #   initialDelaySeconds: 30
          #   timeoutSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8081
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 10

          # resources:
          #   limits:
          #     cpu: 100m
          #     memory: 128Mi
          #   requests:
          #     cpu: 25m
          #     memory: 64Mi
