apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: default
  labels:
    run: hello
spec:
  type: NodePort
  # clusterIP: None
  selector:
    run: hello
  ports:
  - name: http
    port: 8080
    protocol: TCP
